server:
  port: 8101
spring:
  application:
    name: springboot-mybatisPuls-demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:mysql://10.10.1.78:3306/shop_goods?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai
    # 使用p6spy 的配置
    #    url: jdbc:p6spy:mysql://10.10.1.78:3306/shop_goods?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1qaz!QAZ
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 60000
      pool-name: DatebookHikariCP
      max-lifetime: 300000
      connection-timeout: 30000
      connection-test-query: SELECT 1
# ====================MybatisPlus====================
mybatis-plus:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.gupao.springbootdemo.model
  configuration:
    map-underscore-to-camel-case: true
    # mysql日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 逻辑已删除值(默认为 1)
      logic-delete-field: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0


# ------------------------------------LOG日志配置------------------------------------------
farelog:
  appName: ${spring.application.name}
  path: ./logs
  history-days: 1

logging:
  level:
    root: info
  size: 500


# 上传文件路径
update:
  file:
    path: /data/springboot-mybatisPuls-demo/updateFile

thread:
  pool:
    corePoolSize: 64
    maxPoolSize: 128
    queueCapacity: 10000
    keepAliveSeconds: 60000
    threadNamePrefix: myThread

rest:
  connectTimeout: 30000
  socketTimeout: 100000


seaweedfs:
  qz:
    host: 10.10.1.78
    port: 19333
    fullpath: http://10.10.1.78:19333/